### xxl-job executor appname
doux.xxl.job.executor.appname=doux-job-executor
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
doux.xxl.job.executor.address=
### xxl-job executor server-info
doux.xxl.job.executor.ip=
doux.xxl.job.executor.port=9998
### xxl-job executor log-path
doux.xxl.job.executor.logPath=${HOME}/logs/xxl-job/jobhandler
### xxl-job executor log-retention-days
doux.xxl.job.executor.logretentiondays=30
### xxl-job executor thread pool config
doux.xxl.job.executor.pool-core-size=10
doux.xxl.job.executor.pool-maximum-size=50