com:
  allinfinance:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/common-platform?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      druid:
        stat-view-servlet:
          enabled: true
        web-stat-filter:
          enabled: true