spring:
  profiles:
    active: db,web

# token过期时间  默认为7天
token.expire_time: 3600
# refreshToken过期时间  默认为30天
#token.refresh_expire_time: 7
# token 生成秘钥
token.token_secret: f26e587c28064d0e855e72c0a6a0e618
# OTP 二维码生成保存路径
qrCode.path: C:\home\aos\qrcode


# rsa配置
rsa.key.privateKeyFile: C:\\test\\auth\\priKey.key
rsa.key.publicKeyFile: C:\\test\\auth\\pubKey.key
rsa.key.secret: 1@dfj459fhjd4$jfdk#

