jdbc:
  driver: com.ibm.db2.jcc.DB2Driver
  url: jdbc:db2://10.250.23.33:50000/efss:currentSchema=CES_AUTH;
  username: efss
  password: efss
  validationQuery: select 1 from sysibm.sysdummy1


dev:
  batch:
    mapper:
      aop:
        expression: execution(* com.allinfinance.dev.dal.service.*.*(..))
