spring:
  profiles:
    active: db,web


#Cas客户端配置
cas:
  incluster: true
  validation-type: cas
  #CAS服务端地址
  cas-server-url: http://10.250.28.56:8001/cas
  #CAS客户端地址
  cas-client-host: http://10.252.60.56:8082
  #前端首页地址
  cas-front-url: http://10.252.60.56:8000