jdbc:
  driver: com.ibm.db2.jcc.DB2Driver
  url: jdbc:db2://10.250.29.7:50000/smds:currentSchema=SMDSDEV;
  username: smds
  password: smds
  validationQuery: select 1 from sysibm.sysdummy1


dev:
  batch:
    mapper:
      aop:
        expression: execution(* com.allinfinance.dev.dal.service.*.*(..))
