jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://10.250.28.143/iasp_backend
  username: root
  password: allinfinance
  validationQuery: select 1


dev:
  batch:
    mapper:
      aop:
        expression: execution(* com.allinfinance.dev.dal.service.*.*(..))
