spring:
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    password: xxx
    from: xxx@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
