spring:
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    password: xxx
    from: dev-xxl-job@allinfinance.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

management:
  health:
    mail:
      enabled: false