### xxl-job, access token
## xxl-job, triggerPool max size
### xxl-job, log retention days
xxl:
  job:
    accessToken:
    triggerPool:
      fast:
        max: 200
      slow:
        max: 100
    logRetentionDays: 30
    jobGroup:
      appNameRegex: ^[a-z][a-z0-9-]{3,63}$
      titleRegex: ^.{4,12}$
