dev.dubbo.application.name=dubbo-example-provider
dev.dubbo.registry.address=10.252.60.184:2181
dev.dubbo.registry.protocol=zookeeper
dev.dubbo.registry.timeout=10000
dev.dubbo.protocol.name=dubbo
dev.dubbo.protocol.port=31245
dev.dubbo.provider.timeout=10000
dev.dubbo.provider.retries=0
dev.dubbo.consumer.check=false
dev.dubbo.consumer.timeout=10000
dev.dubbo.consumer.retries=0
dev.dubbo.consumer.group=0001
dev.dubbo.consumer.version=1.0.0