jdbc.driver=com.ibm.db2.jcc.DB2Driver
jdbc.url=jdbc:db2://10.250.21.182:50000/ycicdev1:currentSchema=DEV;
jdbc.username=dbycic1
jdbc.password=dbycic1
jdbc.validationQuery=select 1 from TBL_HSM_KEY
jdbc.publicKey=
dev.hsp.mapper.basePackage=com.allinfinance.dev.hsp.mapper
dev.batch.mapper.aop.expression=execution(* com.allinfinance.dev.hsp.service.dal.*.*(..))