jdbc.initialSize=5
jdbc.minIdle=5
jdbc.maxActive=200
jdbc.maxWait=3000
jdbc.timeBER=9000
jdbc.minTimeEI=30000
#jdbc.validationQuery=select * from tbl_bat_ctl
jdbc.testWI=false
jdbc.testOB=false
jdbc.testOR=false
jdbc.psCache=false
jdbc.filters=stat,slf4j,config
jdbc.config.decrypt=false
jdbc.config.decrypt.key=