com.allinfinance.datasource.type=com.alibaba.druid.pool.DruidDataSource
#============================druid's configuration======================================
com.allinfinance.datasource.druid.initial-size=5
com.allinfinance.datasource.druid.min-idle=5
com.allinfinance.datasource.druid.max-active=20
com.allinfinance.datasource.druid.max-wait=60000
com.allinfinance.datasource.druid.time-between-eviction-runs-millis=60000
com.allinfinance.datasource.druid.min-evictable-idle-time-millis=300000
com.allinfinance.datasource.druid.validation-query=SELECT 1
com.allinfinance.datasource.druid.test-while-idle=true
com.allinfinance.datasource.druid.test-on-borrow=false
com.allinfinance.datasource.druid.test-on-return=false
com.allinfinance.datasource.druid.pool-prepared-statements=true
com.allinfinance.datasource.druid.max-pool-prepared-statement-per-connection-size=20
com.allinfinance.datasource.druid.filters=stat,wall
com.allinfinance.datasource.druid.use-global-data-source-stat=true
com.allinfinance.datasource.druid.connect-properties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
com.allinfinance.datasource.druid.stat-view-servlet.login-username=admin
com.allinfinance.datasource.druid.stat-view-servlet.login-password=123456
com.allinfinance.datasource.druid.stat-view-servlet.reset-enable=false
com.allinfinance.datasource.druid.stat-view-servlet.url-pattern=/druid/*
com.allinfinance.datasource.druid.web-stat-filter.url-pattern=/*
com.allinfinance.datasource.druid.web-stat-filter.exclusions=*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
#============================mybatis's configuration======================================
com.allinfinance.datasource.mybatis.mapper-locations=classpath*:/mapper/*Mapper.xml
#============================encryption configuration======================================
com.allinfinance.datasource.encrypt.encrypted=false
com.allinfinance.datasource.transaction.enabled=true