spring:
  application:
    name: dev-gateway
  profiles:
    active: sit

---
spring:
  profiles: dev

com:
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.gateway.service
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12204
        consumer-repeated-reference-limit: 100

---
spring:
  profiles: sit

com:
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.gateway.service
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12204
        consumer-repeated-reference-limit: 100

---
spring:
  profiles: uat

com:
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.gateway.service
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12204
        consumer-repeated-reference-limit: 100


---
spring:
  profiles: prod

com:
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.gateway.service
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12204
        consumer-repeated-reference-limit: 100