com:
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.gateway.service
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.100.79.102:8848/public
        bolt-port: 12204
        consumer-repeated-reference-limit: 100
spring:
  application:
    name: dev-gateway


