spring:
  application:
    name: dev-ccp
  profiles:
    active: dev

---
spring:
  profiles: dev

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.ccp.service

dev:
  ccp:
    file:
      local-sys-path: Z:\work\dev-new\dev\dev-ccp\src\main\resources

---
spring:
  profiles: sit

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-sit
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.ccp.service

---
spring:
  profiles: uat

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-uat
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.ccp.service

---
spring:
  profiles: prod

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.ccp.service