DROP TABLE TBL_BAT_CTL;
CREATE TABLE TBL_BAT_CTL
(
    SYS_ORG_ID      VARCHAR(16) NOT NULL,
    TRIGGER_NAME    VARCHAR(32),
    JOB_DETAIL_NAME VARCHAR(64),
    TARGET_OBJECT   VARCHAR(64) NOT NULL,
    CRON_EXPRESSION VARCHAR(128),
    RECORD_STAT     VARCHAR(1)  NOT NULL,
    JOB_DESC        VARCHAR(64),
    RESERVE_1       VARCHAR(16),
    RESERVE_2       VARCHAR(32),
    RESERVE_3       VARCHAR(64)
);
