CREATE TABLE
    TBL_HSM_KEY
(
    KEY_ID    INTEGER     NOT NULL GENERATED ALWAYS AS IDENTITY,
    KEY_INDEX VARCHAR(16) NOT NULL,
    KEY_VALUE VARCHAR(64) NOT NULL,
    KEY_KCV   VARCHAR(16) NOT NULL,
    ZMK_INDEX VARCHAR(16) NOT NULL,
    PRIMARY KEY (KEY_ID)
);