dev.batch.xxl.job.admin-address=http://127.0.0.1:8080/xxl-job-admin
dev.batch.xxl.job.app-name=dev-batch-demo
#dev.batch.xxl.job.address=
#dev.batch.xxl.job.ip=
dev.batch.xxl.job.port=9949
#dev.batch.xxl.job.access-token=
#dev.batch.xxl.job.log-path=data/applogs/xxl-job/jobhandler
#dev.batch.xxl.job.log-rentention-days=30