jdbc.driver=com.ibm.db2.jcc.DB2Driver
jdbc.url=jdbc:db2://10.250.21.182:50000/ycicdev1:currentSchema=DEV;
jdbc.username=dbycic1
jdbc.password=dbycic1
#jdbc.validationQuery=
jdbc.publicKey=
dev.batch.mapper.basePackage=com.allinfinance.qps.batch.mapper
dev.batch.mapper.aop.expression=execution(* com.allinfinance.qps.batch.service.*.*(..))