spring:
  application:
    name: dev-hsp-tool
  profiles:
    active: dev

nacos:
  config:
    auto-refresh: true
    bootstrap:
      enable: true
    config-long-poll-timeout: 46000
    config-retry-time: 3000
    enable-remote-sync-config: true
    group: DEFAULT_GROUP
    max-retry: 10
    remote-first: true
    type: yaml
    data-id: dev-hsp-tool

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 10000

nacos:
  config:
    namespace: public-yc
    server-addr: 10.250.28.142:8848
    username: iasp-lzk
    password: iasp-lzk

com:
  #  alipay:
  #    sofa:
  #      rpc:
  #        registry-address: nacos://10.250.28.142:8848/wk2021
  #        bolt-port: 10001
  allinfinance:
    rpc:
      consumer:
        common-reference-registry: 10.250.28.142:8848/wkyc2021
        common-reference-list:
          - interface-Name: com.allinfinance.dev.core.util.hsp.SignatureService

---
spring:
  config:
    activate:
      on-profile: yc

server:
  port: 10000

nacos:
  config:
    namespace: public-yc
    server-addr: 10.250.28.142:8848
    username: iasp-lzk
    password: iasp-lzk

com:
  #  alipay:
  #    sofa:
  #      rpc:
  #        registry-address: nacos://10.250.28.142:8848/public-yc
  #        bolt-port: 10001
  allinfinance:
    rpc:
      consumer:
        common-reference-registry: 10.250.28.142:8848/public-yc
        common-reference-list:
          - interface-Name: com.allinfinance.dev.core.util.hsp.SignatureService