com:
  allinfinance:
    connection:
      pool:
        connection-driver: netty
        connection-pool-type: pool
        ping-service: default
      scaffold:
        server-metadata-map:
          server-1:
            server-ip: 127.0.0.1
            server-port: 9999
            ping-enabled: false
          server-2:
            server-ip: 127.0.0.1
            server-port: 9999
            ping-enabled: false
