spring:
  application:
    name: dev-hsp
  profiles:
    active: dev

---
spring:
  profiles: dev

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-hhf
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool-type: queue
      buffer-size: 65536
      server-metadata-map:
        server-1:
          server-name: "加密机1号"
          server-ip: 10.250.28.138
          server-port: 6666
          timeout: 200
          checkout-time: 300000
          retry-times: 3
          max-active-connection: 10
          max-idle-connection: 5
          enable-ping: false
          ping-query-message: "3132333435"
          ping-verify-message: "706f6e67"
        server-2:
          server-name: "加密机2号"
          server-ip: 10.250.28.138
          server-port: 6666
          timeout: 200
          checkout-time: 300000
          retry-times: 3
          max-active-connection: 10
          max-idle-connection: 5
          enable-ping: false
          ping-query-message: "3132333435"
          ping-verify-message: "706f6e67"
        server-3:
          server-name: "加密机3号"
          server-ip: 10.250.28.138
          server-port: 6666
          timeout: 200
          checkout-time: 300000
          retry-times: 3
          max-active-connection: 10
          max-idle-connection: 5
          enable-ping: false
          ping-query-message: "3132333435"
          ping-verify-message: "706f6e67"
        server-4:
          server-name: "加密机4号"
          server-ip: 10.250.28.138
          server-port: 6666
          timeout: 200
          checkout-time: 300000
          retry-times: 3
          max-active-connection: 10
          max-idle-connection: 5
          enable-ping: false
          ping-query-message: "3132333435"
          ping-verify-message: "706f6e67"
    enable-length-field: false

---
spring:
  profiles: sit
  pid:
    file: /data/hsp/config/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-hhf
        bolt-port: 12202
        enabled-ip-range: 10.250.1.17
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool-type: queue
      buffer-size: 65536
      server-metadata-map:
        server-1:
          server-name: "加密机1号"
          server-ip: 10.250.28.138
          server-port: 6666
          timeout: 200
          checkout-time: 300000
          retry-times: 3
          max-active-connection: 10
          max-idle-connection: 5
          enable-ping: false
          ping-query-message: "3132333435"
          ping-verify-message: "706f6e67"
    enable-length-field: false

---
spring:
  profiles: uat
  pid:
    file: /data/hsp/config/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-uat
        bolt-port: 12202
        enabled-ip-range: 10.250.1.17
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool-type: queue
      buffer-size: 65536
      server-metadata-map:
        server-1:
          server-name: "加密机1号"
          server-ip: 10.250.28.138
          server-port: 6666
          timeout: 200
          checkout-time: 300000
          retry-times: 3
          max-active-connection: 10
          max-idle-connection: 5
          enable-ping: false
          ping-query-message: "3132333435"
          ping-verify-message: "706f6e67"
      enable-length-field: false

---
spring:
  profiles: prod
  pid:
    file: /data/hsp/config/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12202
        enabled-ip-range: 10.250.1.17
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool-type: queue
      buffer-size: 65536
      server-metadata-map:
        server-1:
          server-name: "加密机1号"
          server-ip: 10.250.28.138
          server-port: 6666
          timeout: 200
          checkout-time: 300000
          retry-times: 3
          max-active-connection: 10
          max-idle-connection: 5
          enable-ping: false
          ping-query-message: "3132333435"
          ping-verify-message: "706f6e67"
      enable-length-field: false