dev:
  batch:
    mapper:
      aop:
        expression: execution(* com.allinfinance.dev.hsp.service.dal.*.*(..))

jdbc:
  driver: com.ibm.db2.jcc.DB2Driver
  url: jdbc:db2://10.250.20.209:50000/iacsdb
  username: iacs
  password: iacs
  validationQuery: select 1 from TBL_HSM_KEY
  publicKey: