spring:
  application:
    name: dev-hsp
  profiles:
    active: dev

---
spring:
  profiles: dev

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool:
        connection-driver: hsp
        connection-pool-type: pool
        ping-service: default
      scaffold:
        server-metadata-map:
          server-1:
            server-ip: 10.250.28.239
            server-port: 6666
            max-active-connections: 50
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000
          server-2:
            server-ip: 10.250.28.239
            server-port: 6666
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000
    hsp:
      dubbo-enabled: true

dev:
  dubbo:
    application:
      name: dev-hsp
    registry:
      address: 10.250.28.142:8848?namespace=public
      protocol: nacos
      timeout: 10000
    protocol:
      name: dubbo
      port: 32245
    provider:
      timeout: 10000
      retries: 0
    consumer:
      check: false
      timeout: 10000
      retries: 0
    files: file:${HSP_HOME}/hsp-dubbo-config.xml

---
spring:
  profiles: yc
  pid:
    file: ${HOME}/pid/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-yc
        bolt-port: 12202
        enabled-ip-range: 10.250.1.17
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool:
        connection-driver: hsp
        connection-pool-type: pool
        ping-service: default
        warmup: true
      scaffold:
        server-metadata-map:
          server-1:
            server-ip: 10.250.28.239
            server-port: 6666
            max-active-connections: 50
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000
          server-2:
            server-ip: 10.250.28.239
            server-port: 6666
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000

dev:
  dubbo:
    application:
      name: dev-hsp
    registry:
      address: 10.250.28.142:8848?namespace=public-yc
      protocol: nacos
      timeout: 10000
    protocol:
      name: dubbo
      port: 33245
    provider:
      timeout: 10000
      retries: 0
    consumer:
      check: false
      timeout: 10000
      retries: 0
    files: file:${HSP_HOME}/hsp-dubbo-config.xml
---
spring:
  profiles: sit
  pid:
    file: ${HOME}/pid/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12202
        enabled-ip-range: 10.250.1.17
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool:
        connection-driver: hsp
        connection-pool-type: pool
        ping-service: default
        warmup: true
      scaffold:
        server-metadata-map:
          server-1:
            server-ip: 10.250.28.239
            server-port: 6666
            max-active-connections: 50
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000
          server-2:
            server-ip: 10.250.28.239
            server-port: 6666
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000

dev:
  dubbo:
    application:
      name: dev-hsp
    registry:
      address: 10.250.28.142:8848?namespace=public
      protocol: nacos
      timeout: 10000
    protocol:
      name: dubbo
      port: 32245
    provider:
      timeout: 10000
      retries: 0
    consumer:
      check: false
      timeout: 10000
      retries: 0
    files: file:${HSP_HOME}/hsp-dubbo-config.xml

---
spring:
  profiles: uat
  pid:
    file: ${HOME}/pid/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-uat
        bolt-port: 12202
        enabled-ip-range: 10.250.1.17
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool:
        connection-driver: hsp
        connection-pool-type: queue
        ping-service: default
        warmup: true
      scaffold:
        server-metadata-map:
          server-1:
            server-ip: 10.250.28.239
            server-port: 6666
            max-active-connections: 50
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000
          server-2:
            server-ip: 10.250.28.239
            server-port: 6666
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000
    hsp:
      dubbo-enabled: true

dev:
  dubbo:
    application:
      name: dev-hsp
    registry:
      address: 10.250.28.142:8848?namespace=public-uat
      protocol: nacos
      timeout: 10000
    protocol:
      name: dubbo
      port: 32245
    provider:
      timeout: 10000
      retries: 0
    consumer:
      check: false
      timeout: 10000
      retries: 0
    files: file:${HOME}/apps/${spring.application.name}/config/hsp-dubbo-config.xml

---
spring:
  profiles: prod
  pid:
    file: ${HOME}/pid/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.200.1.192:8848/public
        bolt-port: 8001
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service
    connection:
      pool:
        connection-driver: hsp
        connection-pool-type: queue
        ping-service: default
        warmup: true
      scaffold:
        server-metadata-map:
          server-1:
            server-ip: 10.200.4.133
            server-port: 6666
            max-active-connections: 50
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000
          server-2:
            server-ip: 10.200.4.134
            server-port: 6666
            max-active-connections: 50
            ping-enabled: false
            ping-query-content: "00"
            ping-verify-message: ""
            length-field: 2
            buffer-size: 65536
            default-network-timeout: 5000
    hsp:
      dubbo-enabled: true

dev:
  dubbo:
    application:
      name: dev-hsp
    registry:
      address: 10.200.1.192:8848?namespace=public
      protocol: nacos
      timeout: 10000
    protocol:
      name: dubbo
      port: 7001
    provider:
      timeout: 10000
      retries: 0
    consumer:
      check: false
      timeout: 10000
      retries: 0
    files: file:${HOME}/apps/${spring.application.name}/config/hsp-dubbo-config.xml