spring:
  application:
    name: dev-hsp
  profiles:
    active: dev

---
spring:
  profiles: dev

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service

---
spring:
  profiles: sit
  pid:
    file: /app/dev-hsp/config/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-sit
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service

---
spring:
  profiles: uat
  pid:
    file: /app/dev-hsp/config/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public-uat
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service

---
spring:
  profiles: prod
  pid:
    file: /app/dev-hsp/config/${spring.application.name}/${spring.application.name}.pid

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12202
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.hsp.service