com:
  allinfinance:
    socket:
      server:
        bootstrap:
          serverEnabled: true
          bootstrap: default
        scaffold:
          server-metadata-list:
            - name: test1
              port: 12468
#              decodeMsgLength: 4
#              encodeMsgLength: 4
#              decodeCharset: UTF-8
#              encodeCharset: UTF-8
              handlerClassName: com.allinfinance.example.socket.server.handler.TestNettyHandler
#              decoderClassName: com.allinfinance.dev.infrastructure.socket.server.netty.codec.DemuxingMessageDecoder
#              encoderClassName: com.allinfinance.dev.infrastructure.socket.server.netty.codec.DemuxingMessageEncoder
#              serverDriver: netty
            - name: test2
              port: 12469
              decodeMsgLength: 4
              encodeMsgLength: 4
#              decodeCharset: UTF-8
#              encodeCharset: UTF-8
              handlerClassName: com.allinfinance.example.socket.server.handler.TestNettyHandler
#              decoderClassName: com.allinfinance.dev.infrastructure.socket.server.netty.codec.DemuxingMessageDecoder
#              encoderClassName: com.allinfinance.dev.infrastructure.socket.server.netty.codec.DemuxingMessageEncoder
#              serverDriver: netty



