dubbo:
  application:
    name: dubbo-example-provider
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    timeout: 10000
  protocol:
    name: dubbo
    port: 31245
  provider:
    timeout: 10000
    retries: 0
  consumer:
    check: false
    timeout: 10000
    retries: 0