spring:
  application:
    name: rpc-consumer

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.100.79.102:8848/iasp-zy
        bolt-port: 12204
  allinfinance:
    rpc:
      reference-list:
        - com.allinfinance.rpc.scaffold.api.TestApi
        - com.allinfinance.dev.core.util.socket.client.ISocketClientService
        - com.allinfinance.dev.core.util.http.client.IHttpClientService
      bootstrap:
        enable: false
        gate-registry: 10.100.79.102:8848/iasp-zy
        app-unique-id: ${spring.application.name}
        app-list:
          - type: TCP
            listen-port: 8852
            tcp-config:
              decode-msg-length: 4
              encode-msg-length: 4
          - type: TCP
            listen-port: 8863
            tcp-config:
              decode-msg-length: 4
              encode-msg-length: 4
server:
  port: 8085