spring:
  application:
    name: rpc-consumer

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/iasp-zy
        bolt-port: 12204
  allinfinance:
    rpc:
      reference-list:
        - com.allinfinance.rpc.scaffold.api.TestApi
      bootstrap:
        enable: true
        gate-registry: 10.250.28.142:8848/public
        app-unique-id: ${spring.application.name}
        app-list:
          - type: TCP
            listen-port: 8852
            tcp-config:
              decode-msg-length: 4
              encode-msg-length: 4
          - type: HTTP
            listen-port: 8863
            http-config:
              url-list:
                - /api/test
                - /asd/dds