### xxl-job executor appname
com.allinfinance.xxl.job.executor.appname=allinfinance-dev3-executor
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
com.allinfinance.xxl.job.executor.address=
### xxl-job executor server-info
com.allinfinance.xxl.job.executor.ip=
com.allinfinance.xxl.job.executor.port=9998
### xxl-job executor log-path
com.allinfinance.xxl.job.executor.logPath=/logs/xxl-job/jobhandler
### xxl-job executor log-retention-days
com.allinfinance.xxl.job.executor.logretentiondays=30