spring:
  application:
    name: dev-hsp-example

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.250.28.142:8848/public
        bolt-port: 12204
  allinfinance:
    rpc:
      reference-list:
        - com.allinfinance.dev.core.util.hsp.SignatureService

hsp:
  registry:
    address: 10.250.28.142:8848/public

dev:
  dubbo:
    application:
      name: hsp-example
    registry:
      address: 10.250.20.81:8848?namespace=public
      protocol: nacos
      timeout: 10000
    protocol:
      name: dubbo
      port: 31247
    provider:
      timeout: 10000
      retries: 0
    consumer:
      check: false
      timeout: 10000
      retries: 0
    files: file:${QPSP_HOME}/qps-p-dubboConfig.xml
  http:
    httpsTrust: true