com:
  allinfinance:
    rpc:
      provider-package: com.allinfinance.dev.example.socket.service
    dev:
      socket:
        name: "test1"
        port: 13454
        handler-class-name: "com.allinfinance.dev.example.socket.TestIOHandler"
        ext-config:
          - name: "test2"
            port: 13455
            handler-class-name: "com.allinfinance.dev.example.socket.TestIOHandler"
  alipay:
    sofa:
      rpc:
        registry-address: nacos://10.100.79.102:8848/iasp-zy
        bolt-port: 12203
spring:
  application:
    name: socket-example


