dev.socket.handler=com.allinfinance.dev.example.socket.TestIOHandler
dev.socket.appName=dev03
dev.socket.port=4493
dev.socket.bufferSize=256
dev.socket.keepAlive=true
dev.socket.beat.timeout=10
dev.socket.beat.interval=20
#dev.socket.decoder=com.allinfinance.dev.core.util.socket.codec.Message8583Decoder
#dev.socket.encoder=com.allinfinance.dev.core.util.socket.codec.Message8583Encoder